name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: dependencies
      run: sudo apt-get update&&sudo apt-get install -y libc6-dev-i386 lib32ncurses5-dev libx11-dev g++-multilib lib32z1-dev
    - name: get android sdk
      run: wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
    - name: extract android sdk
      run: tar xf android-sdk_r23.0.2-linux.tgz
    - name: Android sdk update 
      run: |
        export ANDROID_HOME=`pwd`/android-sdk-linux
        export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
        ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --filter tools,platform-tools,build-tools-21.0.1,android-16,extra-google-m2repository --no-ui --no-https -a
        ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk --filter extra-android-m2repository --no-ui --no-https -a
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    #- name: build
    #  run: mvn clean install
